"""units.status

Revision ID: 472e5c45ac28
Revises: 99e69e51b52d
Create Date: 2025-01-03 15:54:52.703311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472e5c45ac28'
down_revision = '99e69e51b52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
